# Generated by Django 2.2.5 on 2021-08-31 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210831_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birthday',
            new_name='birthdate',
        ),
    ]
